name: Build Marp Slides

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Corepack
      run: |
        corepack enable
        corepack prepare yarn@4.5.1 --activate

    - name: Install dependencies
      run: yarn install

    - name: Build HTML
      run: yarn build:html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: marp-slides
        path: dist/ 
